services:
  prod-server:
    image: coderoom-frontend:1.0.0
    container_name: production-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env.production
    networks:
      - coderoom

networks:
  coderoom:
    external: true